site_name: 'TestTechDocs'
site_description: 'Some description'
repo_url: https://github.com/tonomusdevportal/test-techdocs
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
  - Issuer & Verifier?: 'issuer_verifier/issuer.md'
