site_name: 'VC4TrustEnablement'
site_description: 'Some description'
repo_url: https://github.com/tonomusdevportal/VC4TrustEnablement
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Wallet:
  - Issuer & Verifier?: 'issuer_verifier/issuer.md'
